### ISSUE TITLE
lseq breaks after one repetition

### ISSUE THREAD

**Issue by Ybriknevets** [ldrolez/clyphx-live11#19]
I have a particular track within my set which uses (lseq) to cycle through different root notes on my push v1 using PUSH SCL ROOT. After one pass through the full sequence which is 2 loops, the PUSH SCL ROOT command ceases to function anywhere else in my session; until I close and reopen it.  Almost every scene in my set uses PUSH SCL ROOT and if I avoid the track that uses (lseq) the command works fine. So it seems (lseq) is borked. Is it possible to fix this?

**Comment by ldrolez** [comment]
Fixed with #59
