### ISSUE TITLE
Is WAITS command missing in Clyphx?

### ISSUE THREAD

**Issue by chebochini** [ldrolez/clyphx-live11#30]
Hello,  I thought WAITS command is not working, but i realized Clyphx is written in Python, so i search the source code and can't find WAIT and WAITS in consts.py

Will these commands be included?
Is there a workaround for recording 2 bars in track X and after that start recording 4 bars in X+1 track?

Something like this:
[] METRO ON; ALL/ARM OFF; 3/sel empty; 3/ARM ON; SRECFIX 2;WAITS 3B; 3/ARM OFF;
4/ARM ON; SRECFIX 1; WAITS 2B; 4/ARM OFF;

Thank you.

**Comment by ldrolez** [comment]
Hi! In release 2.7.6, WAIT and WAITS actions were added. Please test. The main problem is a 100ms-200ms delay because the way the remote script works. Thanks!
