### ISSUE TITLE
X-Controls UserSettings.txt does not work unless installed WITHIN the .app directory.

### ISSUE THREAD

**Issue by rafaelosoto** [ldrolez/clyphx-live11#33]
I figured I would leave this here in case it helps anyone. 

I could not get UserSettings.txt to work in Ableton 11 until I followed some instructions on reddit(https://www.reddit.com/r/ableton/comments/jr41uz/fixed_length_recording_with_any_midi_controller/)

 and installed the ClyphX/ folder within:

/Applications/Ableton Live 11.1 Beta.app/Contents/App-Resources/MIDI Remote Scripts/

to get within the .app you need to right click and 'Show Package Contents'

This is a bit annoying because you will need to constantly update UserSettings.txt within that hidden location, but it works!!

Cheers! This repo rules.

**Comment by ldrolez** [comment]
Ok so it does not work if installed in your user directory?

**Comment by ldrolez** [comment]
fix on the way #35

**Comment by rafaelosoto** [comment]
ran into this bug tonight re-installing and looked up my own ticket 😂 huge thanks for keeping up with this, cheers
