### ISSUE TITLE
ClyphX vanished after working OK

### ISSUE THREAD

**Issue by cesaragustindm** [ldrolez/clyphx-live11#36]
ClyphX was installed and working OK. After a crash it vanished from control surfaces list. 
Tried several things and can't make it come back: restart system, delete ClyphX folder from Remote scripts and copy it back again, total rescan of plugins. 
System:
Windows 10 Home Single Language Version 21H1
Live 11.2.5

**Comment by ldrolez** [comment]
Still happens with new Live versions?
