### ISSUE TITLE
RND function

### ISSUE THREAD

**Issue by Dliver69** [ldrolez/clyphx-live11#45]
RND function isn't working on Mac M1 Ableton version 11.3.10

**Comment by ldrolez** [comment]
Which exact command did you use?

**Comment by ldrolez** [comment]
For me a simple []2/VOL RND works

**Comment by light2peter** [comment]
CLIP NOTES VELO RND looks like it always sets velocity to 64 if I'm reading it correctly: 

https://github.com/ldrolez/clyphx-live11/blob/6f61d170f0f055e6d3033314a5a53271c8ef09af/ClyphX/ClyphXClipActions.py#L722

**Comment by ldrolez** [comment]
Closed by 43015fd69c49810a462dc5b85b9c074403899e5d
