### ISSUE TITLE
Reference.md angle brackets need escaping

### ISSUE THREAD

**Issue by light2peter** [ldrolez/clyphx-live11#52]
The angle brackets don't show in some places in markdown. `CLIP GAIN <x or >x` renders as "CLIP GAIN x"

Could use backticks or `&lt;` and `&gt;`.

Or just switching the order to `CLIP GAIN >x or <x` works: "CLIP GAIN >x or <x" so that markdown doesn't think it's an HTML tag

backticks would probably be nicest so that it gets a fixed-width font

**Comment by ldrolez** [comment]
Thanks! Fixed in 7e112be5dfe1e051a56f9d77f087ae1d51159cc7
